// common
const UPDATE_LOADING = 'UPDATE_LOADING'
const UPDATE_LIST = 'UPDATE_LIST'

// login, logout
const LOGIN = 'LOGIN'
const LOGOUT = 'LOGOUT'
const UPDATE_TOKEN = 'UPDATE_TOKEN'

export {
  UPDATE_LOADING,
  UPDATE_LIST,
  LOGIN,
  LOGOUT,
  UPDATE_TOKEN
}